% Calibration1.m
% README — CAMERA CALIBRATION (CHECKERBOARD)
% ==========================================
%
% WHAT THIS DOES
%   Estimates pinhole intrinsics + radial distortion from checkerboard images,
%   then saves results for planar object measurement scripts.
%
% HOW TO RUN (MATLAB)
%   cd("/Users/home/GSU/Computer_Vision/Computer_Vision/HW1")
%   calibrate_from_folder     % preferred: 20+ images in calibration_images/
%   Calibration1              % legacy: fixed file list below
%
% OUTPUT (same folder)
%   cameraParams.mat           — MATLAB cameraParameters (for measure_object_calibrated.m)
%   camera_calibration.json    — intrinsics for measure_object_calibrated.py
%
% NEXT STEP
%   pick_measurement_points   — click reference + object corners on a photo
%   measure_object_calibrated   (MATLAB)
%   python3 measure_object_calibrated.py   (Python)
%
% Auto-generated by cameraCalibrator app on 19-Sep-2026
%-------------------------------------------------------

% Define images to use for calibration.
imageFileNames = {'/Users/home/Downloads/IMG_5270.jpg',...
    '/Users/home/Downloads/IMG_5271.jpg',...
    '/Users/home/Downloads/IMG_5257.jpg',...
    '/Users/home/Downloads/IMG_5273.jpg',...
    '/Users/home/Downloads/IMG_5275.jpg',...
    '/Users/home/Downloads/IMG_5261.jpg',...
    '/Users/home/Downloads/compressed/IMG_5264.jpg',...
    '/Users/home/Downloads/compressed/IMG_5262.jpg',...
    '/Users/home/Downloads/compressed/IMG_5272.jpg',...
    '/Users/home/Downloads/compressed/IMG_5263.jpg',...
    '/Users/home/Downloads/compressed/IMG_5277.jpg',...
    '/Users/home/Downloads/compressed/IMG_5274.jpg',...
    '/Users/home/Downloads/IMG_5278.jpg',...
    '/Users/home/Downloads/IMG_5279.jpg',...
    '/Users/home/Downloads/IMG_5280.jpg',...
    '/Users/home/Downloads/IMG_5281.jpg',...
    '/Users/home/Downloads/IMG_5282.jpg',...
    '/Users/home/Downloads/IMG_5283.jpg',...
    };

% Detect calibration pattern in images.
minCornerMetric = 0.150000;
isDistortionHigh = false;
[imagePoints, patternDims, imagesUsed] = detectCheckerboardPoints(imageFileNames, ...
    MinCornerMetric=minCornerMetric, HighDistortion=isDistortionHigh);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size.
originalImage = imread(imageFileNames{1});
[mrows, ncols] = size(originalImage, 1:2);

% Generate world coordinates for the planar pattern keypoints.
squareSize = 1.000000;  % inches
worldPoints = patternWorldPoints("checkerboard", patternDims, squareSize);

% Calibrate the camera.
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    EstimateSkew=false, EstimateTangentialDistortion=false, ...
    NumRadialDistortionCoefficients=2, WorldUnits="inches", ...
    InitialK=[], InitialRadialDistortion=[], ImageSize=[mrows ncols]);

% View reprojection errors.
h1 = figure;
showReprojectionErrors(cameraParams);

% Visualize pattern locations.
h2 = figure;
showExtrinsics(cameraParams, "CameraCentric");

% Display parameter estimation errors.
displayErrors(estimationErrors, cameraParams);

% Use the calibration results to undistort the image by removing the effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% Display the undistorted image.
h3 = figure;
imshow(undistortedImage)
title("Undistorted Image");

% Refer to the following examples for workflows you can follow after calibration

% openExample("vision/MeasuringPlanarObjectsExample")
% openExample("vision/StructureFromMotionExample")

% Save calibration for measurement scripts (planar homography + undistortion).
calibrationDir = fileparts(mfilename("fullpath"));
if strlength(calibrationDir) == 0
    calibrationDir = pwd;
end
matPath = fullfile(calibrationDir, "cameraParams.mat");
jsonPath = fullfile(calibrationDir, "camera_calibration.json");
save(matPath, "cameraParams", "squareSize", "patternDims", "worldPoints");
fprintf("Saved MATLAB calibration: %s\n", matPath);
export_camera_calibration(cameraParams, jsonPath);
